language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.6
  - 3.7-dev
  - pypy3.3-5.2-alpha1
script: make travis
install:
  - pip install .
  - pip install -r requirements.txt
after_success:
  - coveralls
